networks:
  app-network:
    driver: bridge

services:
    papernest-back_end:
      build: .
      ports:
        - "8000:8000"
      networks:
        - app-network

    papernest-front_end:
      build: ./front
      ports:
        - "8080:80"
      networks:
        - app-network
